extends:
  - airbnb-base
  - plugin:jsdoc/recommended
plugins:
  - jsdoc
  - chai-friendly
env:
  node: true
  mocha: true
rules:
  no-param-reassign: "off"
  import/no-unresolved:
    - error
    - commonjs: true
      ignore: [ ^aws-sdk$, ^oracledb$, ^request-promise-native$ ]
  import/no-extraneous-dependencies:
    - error
    - devDependencies:
      - '**/tests/**/*.test.js'
      - gulpfile.js
      - '**/aws-operations.js'
  no-unused-expressions: 'off'
  chai-friendly/no-unused-expressions: 'error'
  jsdoc/require-param:
    - warn
    - exemptedBy: [ type ]
  jsdoc/require-returns:
    - warn
    - exemptedBy: [ type ]
  jsdoc/no-undefined-types:
    - warn
      # Express types
    - definedTypes:
        - RequestHandler
        - ErrorRequestHandler
        - Request
        - Response
  jsdoc/require-jsdoc:
    - warn
    - publicOnly: true
      require:
        ArrowFunctionExpression: true
